name: Mac 2.13 Crypto, Core, AppServer
env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 60
    if: "! contains(github.event.pull_request.labels.*.name, 'documentation')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Scala
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'sbt'
      - name: install sbt as workaround https://github.com/actions/setup-java/issues/627
        run: brew install sbt
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.bitcoin-s/binaries
          key: ${{ runner.os }}-wallet-node-dlc-test-cache
      - name: run tests
        run: sbt coverage cryptoTestJVM/test coreTestJVM/test secp256k1jni/test zmq/test appCommonsTest/test asyncUtilsTestJVM/test chainTest/test dlcNodeTest/test appServerTest/test
